version: '3.8'

services:
  app:
    build: .
    container_name: rocketlc_api_app
    ports:
      - "${PORT:-5000}:5000"  # Usa a variável de ambiente PORT, padrão 5000
    environment:
      - PORT=5000
    deploy:
      resources:
        limits:
          cpus: "0.5"  # Limita a 50% de um núcleo
          memory: "512M"  # Limita a 512MB de RAM
    restart: always

